In [1]:
import pint
import json
import jsonata
from IPython.display import JSON, HTML
import pandas as pd

# ── ANSI palette ──────────────────────────────────────────
RESET, BOLD, DIM = "\033[0m", "\033[1m", "\033[2m"
CYAN, GREEN, YELLOW = "\033[36m", "\033[32m", "\033[33m"

reg = pint.UnitRegistry()
reg.define('kg = kilogram')
reg.define('mg = milligram')
reg.define('mcg = microgram')
reg.define('mL = milliliter')
reg.define('ug = microgram')
reg.define('ng = nanogram')
reg.define('cg = centigram')
reg.define('dL = deciliter')
reg.define('L = liter')
reg.define('g = gram')
reg.define('gm = gram')
reg.define('equivalent = [substance_charge] = Eq')
reg.define('meq = 0.001 equivalent = mEq')
reg.define('mEq = 0.001 equivalent = meq')
# Activity / arbitrary units family — all dimensionally [activity]
reg.define('unit = [activity] = U = IU = iu = USP_U = arb_U')
reg.define('milliunit = 0.001 unit = mU = mIU')
reg.define('million_unit = 1e6 unit = MU = MIU')
mass = 1000 * reg.mg
vol = 1000 * reg.mL
conc = mass / vol

UNITS = ("mg/mL", "cg/dL", "ug/mL", "ng/mL", "g/mL", "mg/L", "ug/L", "g/L")


def show_conc(conc, units=UNITS, prec=6):
      """Print a concentration in multiple units as an aligned, colorized table."""
      print(f"{BOLD}{CYAN}CONC:{RESET} {BOLD}{conc:~P}{RESET}")
      w = max(map(len, units))
      for u in units:
            q = conc.to(u)
            print(f"-> {GREEN}{q.magnitude:>7,.{prec}g}{RESET}"
                  f" {RESET} {YELLOW}{u:<{w}}{RESET}")


show_conc(conc)

CONC: 1.0 mg/mL
->       1  mg/mL
->      10  cg/dL
->   1,000  ug/mL
->   1e+06  ng/mL
->   0.001  g/mL
->   1,000  mg/L
->   1e+06  ug/L
->       1  g/L

## FDA

## Functions

In [2]:
import re
import pint
from dataclasses import dataclass
from fda import clean_labeler_name

_STRENGTH_RE = re.compile(
      r'^\s*'
      r'(?P<num_val>\d+(?:\.\d+)?)\s*(?P<num_unit>[a-zA-Zµμ%]+)'
      r'\s*(?:/\s*'
      r'(?P<den_val>\d+(?:\.\d+)?)?\s*(?P<den_unit>[a-zA-Zµμ]+)'
      r')?\s*$'
)
_UCUM_BRACKET_RE = re.compile(r"\[([^\]]+)\]")
# language=JSONata
_JSONATA_PTYPE_EXTRACTOR = r"$ ~> |**[description]|{'product_type': $reverse($match(description, /\b[A-Z\s,\-]{3,}/).match)[0]}|"


def extract_product_type(obj):
      return jsonata.Jsonata(_JSONATA_PTYPE_EXTRACTOR).evaluate(obj)


def _normalize_ucum(s: str) -> str:
      # [USP'U] -> USP_U, [iU] -> iU, [arb'U] -> arb_U
      return _UCUM_BRACKET_RE.sub(
            lambda m: m.group(1).replace("'", "_").replace(".", "_"),
            s,
      )


def _normalize_denom(s: str) -> str:
      # ".9 g/100mL" -> ".9 g/(100mL)"
      return re.sub(r'/\s*(\d*\.?\d+)\s*([a-zA-Z]+)', r'/(\1\2)', s)


def parse_strength(strength_str: str) -> pint.Quantity[pint.Unit]:
      """
      Parse a pharmaceutical strength string into a pint Quantity.
      """
      if not isinstance(strength_str, str) or not strength_str.strip():
            raise ValueError(f"Empty or non-string strength: {strength_str!r}")

      s_str = strength_str.strip().replace('μ', 'u').replace('µ', 'u')  # normalize micro
      s_norm_ucum = _normalize_ucum(s_str)
      s_norm = _normalize_denom(s_norm_ucum)

      m = _STRENGTH_RE.match(s_norm)
      if not m:
            # Fall back to letting pint try directly (handles odd cases pint knows about)
            try:
                  return reg.parse_expression(s_norm)
            except Exception as e:
                  raise ValueError(f"Could not parse strength {strength_str!r}: {e}") from e

      num_val = float(m.group('num_val'))
      num_unit = m.group('num_unit')
      den_unit = m.group('den_unit')
      den_val = float(m.group('den_val')) if m.group('den_val') else 1

      try:
            numerator = num_val * reg.parse_expression(num_unit)
      except pint.errors.UndefinedUnitError as e:
            raise ValueError(f"Unknown numerator unit in {strength_str!r}: {num_unit}") from e

      if den_unit is None:
            return numerator

      try:
            denominator = den_val * reg.parse_expression(den_unit)
      except pint.errors.UndefinedUnitError as e:
            raise ValueError(f"Unknown denominator unit in {strength_str!r}: {den_unit}") from e

      if denominator.magnitude == 0:
            raise ValueError(f"Zero denominator in {strength_str!r}")

      return round(numerator / denominator, 6)


def parse_strength_in_context(obj):
      if isinstance(obj, dict):
            return {
                  k: (parse_strength(v) if k == 'strength' and isinstance(v, str)
                      else parse_strength_in_context(v))
                  for k, v in obj.items()
            }
      if isinstance(obj, list):
            return [parse_strength_in_context(x) for x in obj]
      return obj


def get_product_type(packaging):
      try:
            return packaging[0]['product_type']
      except (IndexError, KeyError, TypeError):
            return None


PACKAGE_PATTERN = re.compile(
      r"/\s*"
      r"(?P<package_size>\d+(?:\.\d+)?\s*[A-Za-zµμ]+)"
      r"\s+in\s+"
      r"(?P<package_count>\d+)\s+"
      r"(?P<package_type>[A-Za-z][A-Za-z,\- ]*?)"
      r"(?=\s*(?:\(|$))",
      re.IGNORECASE,
)


@dataclass
class PackageInfo:
      package_count: int
      package_size: str
      package_type: str


def extract_package_info(value: str) -> PackageInfo | None:
      match = PACKAGE_PATTERN.search(value)

      if not match:
            return None

      return PackageInfo(
            package_count=int(match.group("package_count")),
            package_size=" ".join(match.group("package_size").split()),
            package_type=" ".join(match.group("package_type").split()),
      )

## Usage

### Potassium Phosphates

In [3]:
from rxocrpl.fda import lookup_generic_name, lookup_ndc_package

kpo4 = lookup_generic_name('potassium phosphates', dosage_form='INJECTION', fetch_rxcui=True)
JSON(kpo4)

In [4]:
df = pd.DataFrame(kpo4)
df

,labeler_name,brand_name,generic_name,product_ndc,active_ingredients,dosage_form,route,packaging,rxcui,_matched_via,product_type,packaged_as,package_type,package_size
0,Caplin Steriles Limited,POTASSIUM PHOSPHATES,POTASSIUM PHOSPHATES,65145-195,"[{'name': 'POTASSIUM PHOSPHATE, DIBASIC', 'str...","INJECTION, SOLUTION, CONCENTRATE",[INTRAVENOUS],"[{'package_ndc': '65145-195-25', 'description'...","{'concept': [['1928569', 'SCD']], 'drug': [['1...",generic_name,"VIAL, SINGLE-DOSE","{'packageCount': 1, 'packageSize': '15 mL', 'p...","VIAL, SINGLE-DOSE",15 mL
1,Caplin Steriles Limited,POTASSIUM PHOSPHATES,POTASSIUM PHOSPHATES,65145-194,"[{'name': 'POTASSIUM PHOSPHATE, DIBASIC', 'str...","INJECTION, SOLUTION, CONCENTRATE",[INTRAVENOUS],"[{'package_ndc': '65145-194-25', 'description'...","{'concept': [['1928567', 'SCD']], 'drug': [['1...",generic_name,"VIAL, SINGLE-DOSE","{'packageCount': 1, 'packageSize': '5 mL', 'pa...","VIAL, SINGLE-DOSE",5 mL
2,Caplin Steriles Limited,POTASSIUM PHOSPHATES,POTASSIUM PHOSPHATES,65145-196,"[{'name': 'POTASSIUM PHOSPHATE, DIBASIC', 'str...","INJECTION, SOLUTION, CONCENTRATE",[INTRAVENOUS],"[{'package_ndc': '65145-196-25', 'description'...","{'concept': [['2667657', 'SCD']], 'drug': [['2...",generic_name,"VIAL, PHARMACY BULK PACKAGE","{'packageCount': 1, 'packageSize': '50 mL', 'p...","VIAL, PHARMACY BULK PACKAGE",50 mL
3,"Fresenius Kabi USA, LLC",Potassium Phosphates,Potassium Phosphates,65219-656,"[{'name': 'DIBASIC POTASSIUM PHOSPHATE', 'stre...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-656-10', 'description'...","{'concept': [['2716829', 'SCD']], 'drug': [['2...",generic_name,POUCH,"{'packageCount': 1, 'packageSize': '1 BAG', 'p...",POUCH,1 BAG
4,"Fresenius Kabi USA, LLC",Potassium Phosphates,Potassium Phosphates,65219-658,"[{'name': 'DIBASIC POTASSIUM PHOSPHATE', 'stre...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-658-25', 'description'...","{'concept': [['2688947', 'SCD']], 'drug': [['2...",generic_name,POUCH,"{'packageCount': 1, 'packageSize': '1 BAG', 'p...",POUCH,1 BAG
5,"Hospira, Inc.",Potassium Phosphates,potassium phosphates,0409-0032,"[{'name': 'DIBASIC POTASSIUM PHOSPHATE', 'stre...","INJECTION, SOLUTION, CONCENTRATE",[INTRAVENOUS],"[{'package_ndc': '0409-0032-01', 'description'...","{'concept': [['1928569', 'SCD']], 'drug': [['1...",generic_name,"VIAL, SINGLE-DOSE","{'packageCount': 1, 'packageSize': '15 mL', 'p...","VIAL, SINGLE-DOSE",15 mL
6,"GLENMARK PHARMACEUTICALS INC., USA",POTASSIUM PHOSPHATES,POTASSIUM PHOSPHATES,68462-788,"[{'name': 'DIBASIC POTASSIUM PHOSPHATE', 'stre...","INJECTION, SOLUTION, CONCENTRATE",[INTRAVENOUS],"[{'package_ndc': '68462-788-25', 'description'...","{'concept': [['2667657', 'SCD']], 'drug': [['2...",generic_name,"VIAL, PHARMACY BULK PACKAGE","{'packageCount': 1, 'packageSize': '50 mL', 'p...","VIAL, PHARMACY BULK PACKAGE",50 mL
7,"GLENMARK PHARMACEUTICALS INC., USA",POTASSIUM PHOSPHATES,POTASSIUM PHOSPHATES,68462-786,"[{'name': 'DIBASIC POTASSIUM PHOSPHATE', 'stre...","INJECTION, SOLUTION, CONCENTRATE",[INTRAVENOUS],"[{'package_ndc': '68462-786-25', 'description'...","{'concept': [['1928567', 'SCD']], 'drug': [['1...",generic_name,"VIAL, SINGLE-DOSE","{'packageCount': 1, 'packageSize': '5 mL', 'pa...","VIAL, SINGLE-DOSE",5 mL
8,"GLENMARK PHARMACEUTICALS INC., USA",POTASSIUM PHOSPHATES,POTASSIUM PHOSPHATES,68462-787,"[{'name': 'DIBASIC POTASSIUM PHOSPHATE', 'stre...","INJECTION, SOLUTION, CONCENTRATE",[INTRAVENOUS],"[{'package_ndc': '68462-787-25', 'description'...","{'concept': [['1928569', 'SCD']], 'drug': [['1...",generic_name,"VIAL, SINGLE-DOSE","{'packageCount': 1, 'packageSize': '15 mL', 'p...","VIAL, SINGLE-DOSE",15 mL
9,Cipla USA Inc.,Potassium Phosphates,Potassium Phosphates,69097-055,"[{'name': 'DIBASIC POTASSIUM PHOSPHATE', 'stre...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '69097-055-97', 'description'...","{'concept': [['2667657', 'SCD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '50 mL', 'p...",VIAL,50 mL
10,Cipla USA Inc.,Potassium Phosphates,Potassium Phosphates,69097-078,"[{'name': 'DIBASIC POTASSIUM PHOSPHATE', 'stre...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '69097-078-97', 'description'...","{'concept': [['1928567', 'SCD']], 'drug': [['1...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '5 mL', 'pa...",VIAL,5 mL
11,Cipla USA Inc.,Potassium Phosphates,Potassium Phosphates,69097-077,"[{'name': 'DIBASIC POTASSIUM PHOSPHATE', 'stre...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '69097-077-97', 'description'...","{'concept': [['1928569', 'SCD']], 'drug': [['1...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '15 mL', 'p...",VIAL,15 mL
12,"American Regent, Inc.",Potassium Phosphates,potassium phosphates,0517-2051,"[{'name': 'POTASSIUM PHOSPHATE, DIBASIC', 'str...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0517-2051-25', 'description'...","{'concept': [['1928567', 'SCD']], 'drug': [['1...",generic_name,"VIAL, SINGLE-DOSE","{'packageCount': 1, 'packageSize': '5 mL', 'pa...","VIAL, SINGLE-DOSE",5 mL
13,Amneal Pharmaceuticals LLC,POTASSIUM PHOSPHATES,Potassium Phosphates in sodium chloride,70121-1722,"[{'name': 'POTASSIUM PHOSPHATE, DIBASIC', 'str...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '70121-1722-9', 'description'...","{'concept': [['2688947', 'SCD']], 'drug': [['2...",generic_name,POUCH,"{'packageCount': 1, 'packageSize': '250 mL', '...",BAG,250 mL

In [5]:
# language=JSONata
data = jsonata.Jsonata("""
    *.packaging[$contains(description, 'BAG')].{
        'labeler_name': %.labeler_name,
        'brand_name': %.brand_name,
        'generic_name': %.generic_name,
        'product_ndc': %.product_ndc,
        'active_ingredients': %.active_ingredients,
        'package_ndc': package_ndc,
        'description': description
    }
""").evaluate(kpo4)
df = pd.DataFrame(data)
df

,labeler_name,brand_name,generic_name,product_ndc,active_ingredients,package_ndc,description
0,"Fresenius Kabi USA, LLC",Potassium Phosphates,Potassium Phosphates,65219-656,"[{'name': 'DIBASIC POTASSIUM PHOSPHATE', 'stre...",65219-656-10,24 POUCH in 1 CARTON (65219-656-10) / 1 BAG i...
1,"Fresenius Kabi USA, LLC",Potassium Phosphates,Potassium Phosphates,65219-658,"[{'name': 'DIBASIC POTASSIUM PHOSPHATE', 'stre...",65219-658-25,30 POUCH in 1 CARTON (65219-658-25) / 1 BAG i...
2,Amneal Pharmaceuticals LLC,POTASSIUM PHOSPHATES,Potassium Phosphates in sodium chloride,70121-1722,"[{'name': 'POTASSIUM PHOSPHATE, DIBASIC', 'str...",70121-1722-9,24 POUCH in 1 CARTON (70121-1722-9) / 1 BAG i...

In [6]:
# language=JSONata
print('BAGS:', jsonata.Jsonata("packaging[$contains(description, 'BAG')] ~> $count()").evaluate(kpo4))
# language=JSONata
print('VIALS:', jsonata.Jsonata("packaging[$contains(description, 'VIAL')] ~> $count()").evaluate(kpo4))

BAGS: 3
VIALS: 11

In [7]:
# language=JSONata
res = jsonata.Jsonata("""$.[
            labeler_name,
            product_ndc,
            route,
            [active_ingredients]
      ]""").evaluate(kpo4)

rows = []

for labeler_name, product_ndc, route, ingredients in res:
      for ing in ingredients:
            s = parse_strength(ing["strength"])  # pint.Quantity

            strength_mg_ml = s.to("mg/mL")

            rows.append({
                  "labeler_name": labeler_name,
                  "product_ndc": product_ndc,
                  "name": ing["name"],
                  "route": route,
                  "strength": str(s),
                  "str/mL": float(strength_mg_ml.magnitude),
                  "str_unit": str((strength_mg_ml * reg.mL).units),
            })

df = pd.DataFrame(rows)
df

,labeler_name,product_ndc,name,route,strength,str/mL,str_unit
0,Caplin Steriles Limited,65145-195,"POTASSIUM PHOSPHATE, DIBASIC",INTRAVENOUS,236.0 mg / mL,236.00,mg
1,Caplin Steriles Limited,65145-195,"POTASSIUM PHOSPHATE, MONOBASIC",INTRAVENOUS,224.0 mg / mL,224.00,mg
2,Caplin Steriles Limited,65145-194,"POTASSIUM PHOSPHATE, DIBASIC",INTRAVENOUS,236.0 mg / mL,236.00,mg
3,Caplin Steriles Limited,65145-194,"POTASSIUM PHOSPHATE, MONOBASIC",INTRAVENOUS,224.0 mg / mL,224.00,mg
4,Caplin Steriles Limited,65145-196,"POTASSIUM PHOSPHATE, DIBASIC",INTRAVENOUS,236.0 mg / mL,236.00,mg
5,Caplin Steriles Limited,65145-196,"POTASSIUM PHOSPHATE, MONOBASIC",INTRAVENOUS,224.0 mg / mL,224.00,mg
6,"Fresenius Kabi USA, LLC",65219-656,DIBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,11.8 mg / mL,11.80,mg
7,"Fresenius Kabi USA, LLC",65219-656,MONOBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,11.2 mg / mL,11.20,mg
8,"Fresenius Kabi USA, LLC",65219-658,DIBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,4.72 mg / mL,4.72,mg
9,"Fresenius Kabi USA, LLC",65219-658,MONOBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,4.48 mg / mL,4.48,mg
10,"Hospira, Inc.",0409-0032,DIBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,236.0 mg / mL,236.00,mg
11,"Hospira, Inc.",0409-0032,MONOBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,224.0 mg / mL,224.00,mg
12,"GLENMARK PHARMACEUTICALS INC., USA",68462-788,DIBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,236.0 mg / mL,236.00,mg
13,"GLENMARK PHARMACEUTICALS INC., USA",68462-788,MONOBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,224.0 mg / mL,224.00,mg
14,"GLENMARK PHARMACEUTICALS INC., USA",68462-786,DIBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,236.0 mg / mL,236.00,mg
15,"GLENMARK PHARMACEUTICALS INC., USA",68462-786,MONOBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,224.0 mg / mL,224.00,mg
16,"GLENMARK PHARMACEUTICALS INC., USA",68462-787,DIBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,236.0 mg / mL,236.00,mg
17,"GLENMARK PHARMACEUTICALS INC., USA",68462-787,MONOBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,224.0 mg / mL,224.00,mg
18,Cipla USA Inc.,69097-055,DIBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,236.0 mg / mL,236.00,mg
19,Cipla USA Inc.,69097-055,MONOBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,224.0 mg / mL,224.00,mg
20,Cipla USA Inc.,69097-078,DIBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,236.0 mg / mL,236.00,mg
21,Cipla USA Inc.,69097-078,MONOBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,224.0 mg / mL,224.00,mg
22,Cipla USA Inc.,69097-077,DIBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,236.0 mg / mL,236.00,mg
23,Cipla USA Inc.,69097-077,MONOBASIC POTASSIUM PHOSPHATE,INTRAVENOUS,224.0 mg / mL,224.00,mg
24,"American Regent, Inc.",0517-2051,"POTASSIUM PHOSPHATE, DIBASIC",INTRAVENOUS,236.0 mg / mL,236.00,mg
25,"American Regent, Inc.",0517-2051,"POTASSIUM PHOSPHATE, MONOBASIC",INTRAVENOUS,224.0 mg / mL,224.00,mg
26,Amneal Pharmaceuticals LLC,70121-1722,"POTASSIUM PHOSPHATE, DIBASIC",INTRAVENOUS,4.72 mg / mL,4.72,mg
27,Amneal Pharmaceuticals LLC,70121-1722,"POTASSIUM PHOSPHATE, MONOBASIC",INTRAVENOUS,4.48 mg / mL,4.48,mg

### Sodium Chloride Bags

In [8]:
ns_bag = lookup_generic_name(ingredient_names=['sodium chloride'], dosage_form='INJECTION', max_active_ingredients=1,
                             fetch_rxcui=True)
df = pd.DataFrame(ns_bag)
df = df[df["product_type"] == 'BAG']
df['strength'] = df['active_ingredients'].apply(lambda ings: parse_strength(ings[0]['strength']) if ings else None)
df['strength'] = df['strength'].apply(
      lambda s: round(s.to("mg/mL"), 6) if s is not None else None
)
df

,labeler_name,brand_name,generic_name,product_ndc,active_ingredients,dosage_form,route,packaging,rxcui,_matched_via,product_type,packaged_as,package_type,package_size,strength
1,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-472,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-472-20', 'description'...","{'concept': [['1807634', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '500 mL', '...",BAG,500 mL,9.0 mg / mL
3,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-474,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-474-10', 'description'...","{'concept': [['1807639', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,9.0 mg / mL
4,"Fresenius Kabi USA, LLC",Sodium Chloride,SODIUM CHLORIDE,65219-328,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-328-50', 'description'...","{'concept': [['1807639', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,9.0 mg / mL
7,"Fresenius Medical Care de Mexico, S.A. de C.V.",Sodium Chloride,Sodium Chloride,46163-300,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '46163-300-10', 'description'...","{'concept': [['1807639', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,9.0 mg / mL
10,Baxter Healthcare Corporation,SODIUM CHLORIDE,sodium chloride,0338-9661,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 g/...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0338-9661-60', 'description'...","{'concept': [['1807632', 'SCD']], 'drug': [['1...",other,BAG,None,NaN,NaN,9.0 mg / mL
11,Baxter Healthcare Corporation,SODIUM CHLORIDE,sodium chloride,0338-9662,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '0338-9662-35', 'description'...","{'concept': [['1807632', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '100 mL', '...",BAG,100 mL,9.0 mg / mL
12,"Fresenius Kabi USA, LLC",Sodium Chloride,SODIUM CHLORIDE,65219-432,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-432-85', 'description'...","{'concept': [['1807634', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '500 mL', '...",BAG,500 mL,9.0 mg / mL
13,Baxter Healthcare Corporation,SODIUM CHLORIDE,sodium chloride,0338-9663,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 g/...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0338-9663-60', 'description'...","{'concept': [['1807632', 'SCD']], 'drug': [['1...",other,BAG,None,NaN,NaN,9.0 mg / mL
15,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-470,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-470-30', 'description'...","{'concept': [['1807633', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '250 mL', '...",BAG,250 mL,9.0 mg / mL
16,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-466,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-466-60', 'description'...","{'concept': [['1807631', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '50 mL', 'p...",BAG,50 mL,9.0 mg / mL
17,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-468,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-468-50', 'description'...","{'concept': [['1807632', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '100 mL', '...",BAG,100 mL,9.0 mg / mL
18,"HF Acquisition Co LLC, DBA HealthFirst",0.9% SODIUM CHLORIDE,0.9% SODIUM CHLORIDE,51662-1517,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '51662-1517-1', 'description'...","{'concept': [['1807633', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '250 mL', '...",BAG,250 mL,9.0 mg / mL
19,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-504,"[{'name': 'SODIUM CHLORIDE', 'strength': '.9 g...","INJECTION, SOLUTION",[IRRIGATION],"[{'package_ndc': '65219-504-20', 'description'...","{'concept': [['486515', 'SCD']], 'drug': [['48...",other,BAG,"{'packageCount': 1, 'packageSize': '2000 mL', ...",BAG,2000 mL,9.0 mg / mL
20,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-502,"[{'name': 'SODIUM CHLORIDE', 'strength': '.9 g...","INJECTION, SOLUTION",[IRRIGATION],"[{'package_ndc': '65219-502-10', 'description'...","{'concept': [['486515', 'SCD']], 'drug': [['48...",other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,9.0 mg / mL
21,"HF Acquisition Co LLC, DBA HealthFirst",0.9% SODIUM CHLORIDE,0.9% SODIUM CHLORIDE,51662-1518,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '51662-1518-1', 'description'...","{'concept': [['1807639', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,9.0 mg / mL
22,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-506,"[{'name': 'SODIUM CHLORIDE', 'strength': '.9 g...","INJECTION, SOLUTION",[IRRIGATION],"[{'package_ndc': '65219-506-30', 'description'...","{'concept': [['486515', 'SCD']], 'drug': [['48...",other,BAG,"{'packageCount': 1, 'packageSize': '3000 mL', ...",BAG,3000 mL,9.0 mg / mL
23,"HF Acquisition Co LLC, DBA HealthFirst",0.9% SODIUM CHLORIDE,0.9% SODIUM CHLORIDE,51662-1520,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '51662-1520-1', 'description'...","{'concept': [['1807632', 'SCD']], 'drug': [['1...",other,BAG,None,NaN,NaN,9.0 mg / mL
24,"HF Acquisition Co LLC, DBA HealthFirst",SODIUM CHLORIDE,SODIUM CHLORIDE,51662-1522,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '51662-1522-1', 'description'...","{'concept': [['1807634', 'SCD']], 'drug': [['1...",other,BAG,None,NaN,NaN,9.0 mg / mL
25,CODAN US CORPORATION,Sodium Chloride,SODIUM CHLORIDE,81826-001,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 g/...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '81826-001-01', 'description'...","{'concept': [['1807631', 'SCD'], ['1807632', '...",other,BAG,"{'packageCount': 1, 'packageSize': '50 mL', 'p...",BAG,50 mL,9.0 mg / mL
26,Baxter Healthcare Corporation,SODIUM CHLORIDE,sodium chloride,0338-0162,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '0338-0162-01', 'description'...","{'concept': [['1807632', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '100 mL', '...",BAG,100 mL,9.0 mg / mL
27,Baxter Healthcare Corporation,SODIUM CHLORIDE,sodium chloride,0338-0164,"[{'name': 'SODIUM CHLORIDE', 'strength': '450 ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '0338-0164-01', 'description'...","{'concept': [['1807631', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '50 mL', 'p...",BAG,50 mL,4.5 mg / mL
28,HAVER FARMA ILAC ANONIM SIRKETI,ISOTONIC SODIUM CHLORIDE,biofleks ISOTONIC SODIUM CHLORIDE STERILE,85184-0001,"[{'name': 'SODIUM CHLORIDE', 'strength': '.9 g...",INJECTION,"[INTRAMUSCULAR, INTRAVENOUS, IRRIGATION, SUBCU...","[{'package_ndc': '85184-0001-1', 'description'...","{'concept': [['1807632', 'SCD'], ['1807639', '...",other,BAG,None,NaN,NaN,9.0 mg / mL
29,"Fresenius Medical Care Renal Therapies Group, LLC",Sodium Chloride,Sodium Chloride,49230-300,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '49230-300-10', 'description'...","{'concept': [['1807639', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,9.0 mg / mL
30,Baxter Healthcare Corporation,SODIUM CHLORIDE,sodium chloride,0338-0166,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '0338-0166-01', 'description'...","{'concept': [['1807632', 'SCD']], 'drug': [['1...",other,BAG,"{'packageCount': 1, 'packageSize': '100 mL', '...",BAG,100 mL,9.0 mg / mL

In [9]:
ns_bag = lookup_generic_name(ingredient_names=['sodium chloride'], dosage_form='INJECTION', max_active_ingredients=2)
df = pd.DataFrame(ns_bag)
df = df[df["product_type"] == 'BAG']
df['strength'] = df['active_ingredients'].apply(
      lambda ings: [round(parse_strength(ing['strength']), 5) for ing in ings] if ings else None)
df

,labeler_name,brand_name,generic_name,product_ndc,active_ingredients,dosage_form,route,packaging,rxcui,_matched_via,product_type,packaged_as,package_type,package_size,strength
1,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-472,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-472-20', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '500 mL', '...",BAG,500 mL,[9.0 mg / mL]
3,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-474,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-474-10', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,[9.0 mg / mL]
5,"Fresenius Kabi USA, LLC",Sodium Chloride,SODIUM CHLORIDE,65219-328,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-328-50', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,[9.0 mg / mL]
7,"Fresenius Kabi USA, LLC",Potassium Chloride in Sodium Chloride,Sodium Chloride and Potassium Chloride,63323-686,"[{'name': 'POTASSIUM CHLORIDE', 'strength': '1...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '63323-686-10', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,"[1.5 mg / mL, 9.0 mg / mL]"
8,Baxter Healthcare Company,Potassium Chloride in Sodium Chloride,Potassium Chloride and Sodium Chloride,0338-0695,"[{'name': 'POTASSIUM CHLORIDE', 'strength': '3...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0338-0695-04', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,"[3.0 mg / mL, 9.0 mg / mL]"
9,"Fresenius Kabi USA, LLC",Potassium Chloride in Sodium Chloride,Sodium Chloride and Potassium Chloride,63323-688,"[{'name': 'POTASSIUM CHLORIDE', 'strength': '3...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '63323-688-10', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,"[3.0 mg / mL, 9.0 mg / mL]"
11,"Fresenius Medical Care de Mexico, S.A. de C.V.",Sodium Chloride,Sodium Chloride,46163-300,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '46163-300-10', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,[9.0 mg / mL]
14,Baxter Healthcare Corporation,SODIUM CHLORIDE,sodium chloride,0338-9661,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 g/...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0338-9661-60', 'description'...",None,other,BAG,None,NaN,NaN,[0.009 g / mL]
16,Baxter Healthcare Company,Potassium Chloride in Sodium Chloride,Potassium Chloride and Sodium Chloride,0338-0704,"[{'name': 'POTASSIUM CHLORIDE', 'strength': '1...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0338-0704-34', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,"[1.5 mg / mL, 4.5 mg / mL]"
17,Baxter Healthcare Corporation,SODIUM CHLORIDE,sodium chloride,0338-9662,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '0338-9662-35', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '100 mL', '...",BAG,100 mL,[9.0 mg / mL]
19,"Fresenius Kabi USA, LLC",Sodium Chloride,SODIUM CHLORIDE,65219-432,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-432-85', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '500 mL', '...",BAG,500 mL,[9.0 mg / mL]
20,Baxter Healthcare Corporation,SODIUM CHLORIDE,sodium chloride,0338-9663,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 g/...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0338-9663-60', 'description'...",None,other,BAG,None,NaN,NaN,[0.009 g / mL]
22,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-470,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-470-30', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '250 mL', '...",BAG,250 mL,[9.0 mg / mL]
23,Baxter Healthcare Company,Dextrose and Sodium Chloride,Dextrose and Sodium Chloride,0338-0073,"[{'name': 'DEXTROSE MONOHYDRATE', 'strength': ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0338-0073-04', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,"[0.025 g / mL, 4.5 mg / mL]"
24,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-466,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-466-60', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '50 mL', 'p...",BAG,50 mL,[9.0 mg / mL]
25,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-468,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 mg...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-468-50', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '100 mL', '...",BAG,100 mL,[9.0 mg / mL]
26,"HF Acquisition Co LLC, DBA HealthFirst",0.9% SODIUM CHLORIDE,0.9% SODIUM CHLORIDE,51662-1517,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '51662-1517-1', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '250 mL', '...",BAG,250 mL,[9.0 mg / mL]
27,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-504,"[{'name': 'SODIUM CHLORIDE', 'strength': '.9 g...","INJECTION, SOLUTION",[IRRIGATION],"[{'package_ndc': '65219-504-20', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '2000 mL', ...",BAG,2000 mL,[0.009 g / mL]
28,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-502,"[{'name': 'SODIUM CHLORIDE', 'strength': '.9 g...","INJECTION, SOLUTION",[IRRIGATION],"[{'package_ndc': '65219-502-10', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,[0.009 g / mL]
29,"HF Acquisition Co LLC, DBA HealthFirst",0.9% SODIUM CHLORIDE,0.9% SODIUM CHLORIDE,51662-1518,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '51662-1518-1', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,[9.0 mg / mL]
30,"Fresenius Kabi USA, LLC",Sodium chloride,SODIUM CHLORIDE,65219-506,"[{'name': 'SODIUM CHLORIDE', 'strength': '.9 g...","INJECTION, SOLUTION",[IRRIGATION],"[{'package_ndc': '65219-506-30', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '3000 mL', ...",BAG,3000 mL,[0.009 g / mL]
31,"HF Acquisition Co LLC, DBA HealthFirst",0.9% SODIUM CHLORIDE,0.9% SODIUM CHLORIDE,51662-1520,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '51662-1520-1', 'description'...",None,other,BAG,None,NaN,NaN,[9.0 mg / mL]
32,"HF Acquisition Co LLC, DBA HealthFirst",SODIUM CHLORIDE,SODIUM CHLORIDE,51662-1522,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '51662-1522-1', 'description'...",None,other,BAG,None,NaN,NaN,[9.0 mg / mL]
33,CODAN US CORPORATION,Sodium Chloride,SODIUM CHLORIDE,81826-001,"[{'name': 'SODIUM CHLORIDE', 'strength': '9 g/...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '81826-001-01', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '50 mL', 'p...",BAG,50 mL,[0.009 g / mL]
34,Baxter Healthcare Corporation,SODIUM CHLORIDE,sodium chloride,0338-0162,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '0338-0162-01', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '100 mL', '...",BAG,100 mL,[9.0 mg / mL]
35,Baxter Healthcare Company,Dextrose and Sodium Chloride,Dextrose and Sodium Chloride,0338-0077,"[{'name': 'DEXTROSE MONOHYDRATE', 'strength': ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0338-0077-02', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '250 mL', '...",BAG,250 mL,"[0.05 g / mL, 2.0 mg / mL]"
36,"Fresenius Kabi USA, LLC",Dextrose and Sodium Chloride,DEXTROSE MONOHYDRATE and SODIUM CHLORIDE,63323-870,"[{'name': 'DEXTROSE MONOHYDRATE', 'strength': ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '63323-870-10', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '500 mL', '...",BAG,500 mL,"[0.05 g / mL, 0.009 g / mL]"
37,"Fresenius Kabi USA, LLC",Dextrose and Sodium Chloride,DEXTROSE MONOHYDRATE and SODIUM CHLORIDE,63323-867,"[{'name': 'DEXTROSE MONOHYDRATE', 'strength': ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '63323-867-10', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,"[0.05 g / mL, 0.003 g / mL]"
38,"Fresenius Kabi USA, LLC",Dextrose and Sodium Chloride,DEXTROSE MONOHYDRATE and SODIUM CHLORIDE,63323-869,"[{'name': 'DEXTROSE MONOHYDRATE', 'strength': ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '63323-869-10', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,"[0.05 g / mL, 0.0045 g / mL]"
39,"Fresenius Kabi USA, LLC",Dextrose and Sodium Chloride,DEXTROSE MONOHYDRATE and SODIUM CHLORIDE,63323-873,"[{'name': 'DEXTROSE MONOHYDRATE', 'strength': ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '63323-873-10', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,"[0.05 g / mL, 0.00225 g / mL]"
40,Baxter Healthcare Corporation,SODIUM CHLORIDE,sodium chloride,0338-0164,"[{'name': 'SODIUM CHLORIDE', 'strength': '450 ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '0338-0164-01', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '50 mL', 'p...",BAG,50 mL,[4.5 mg / mL]
41,HAVER FARMA ILAC ANONIM SIRKETI,ISOTONIC SODIUM CHLORIDE,biofleks ISOTONIC SODIUM CHLORIDE STERILE,85184-0001,"[{'name': 'SODIUM CHLORIDE', 'strength': '.9 g...",INJECTION,"[INTRAMUSCULAR, INTRAVENOUS, IRRIGATION, SUBCU...","[{'package_ndc': '85184-0001-1', 'description'...",None,other,BAG,None,NaN,NaN,[0.009 g / mL]
42,"Fresenius Medical Care Renal Therapies Group, LLC",Sodium Chloride,Sodium Chloride,49230-300,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '49230-300-10', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,[9.0 mg / mL]
43,"Fresenius Kabi USA, LLC",DEXTROSE AND SODIUM CHLORIDE,"DEXTROSE MONOHYDRATE, SODIUM CHLORIDE",63323-874,"[{'name': 'DEXTROSE MONOHYDRATE', 'strength': ...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '63323-874-10', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '1000 mL', ...",BAG,1000 mL,"[0.025 g / mL, 0.0045 g / mL]"
44,Baxter Healthcare Corporation,SODIUM CHLORIDE,sodium chloride,0338-0166,"[{'name': 'SODIUM CHLORIDE', 'strength': '900 ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '0338-0166-01', 'description'...",None,other,BAG,"{'packageCount': 1, 'packageSize': '100 mL', '...",BAG,100 mL,[9.0 mg / mL]

### Ceftazidime-Avibactam (Avycaz)

In [10]:
avicaz = lookup_generic_name(ingredient_names=["avibactam", "ceftazidime"], fetch_rxcui=True)
avicaz = extract_product_type(avicaz)
df = pd.DataFrame(avicaz)
df

,labeler_name,brand_name,generic_name,product_ndc,active_ingredients,dosage_form,route,packaging,rxcui,_matched_via,product_type,packaged_as,package_type
0,"Allergan, Inc.",AVYCAZ,"ceftazidime, avibactam",0456-2700,"[{'name': 'AVIBACTAM SODIUM', 'strength': '.5 ...","POWDER, FOR SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0456-2700-10', 'description'...","{'concept': [['1603845', 'SBD']], 'drug': [['1...",other,"VIAL, SINGLE-DOSE",None,None
1,Fresenius Kabi iPSUM S.r.l.,NaN,"CEFTAZIDIME, AVIBACTAM SODIUM",66558-0212,"[{'name': 'AVIBACTAM SODIUM', 'strength': '.2 ...",POWDER,None,"[{'package_ndc': '66558-0212-0', 'description'...",{},other,CONTAINER,None,None

In [11]:
vaso = lookup_generic_name('vasopressin', dosage_form='INJECTION', fetch_rxcui=True)
data = parse_strength_in_context(vaso)
df = pd.DataFrame(data)
df

,labeler_name,brand_name,generic_name,product_ndc,active_ingredients,dosage_form,route,packaging,rxcui,_matched_via,product_type,packaged_as,package_type,package_size
0,"Par Health USA, LLC",Vasostrict,Vasopressin,42023-190,"[{'name': 'VASOPRESSIN, UNSPECIFIED', 'strengt...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '42023-190-01', 'description'...","{'concept': [['1593738', 'SBD']], 'drug': [['3...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '10 mL', 'p...",VIAL,10 mL
1,Gland Pharma Limited,Vasopressin,Vasopressin,68083-663,"[{'name': 'VASOPRESSIN', 'strength': 0.4 unit ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '68083-663-10', 'description'...","{'concept': [['2399907', 'SCD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '100 mL', '...",VIAL,100 mL
2,"Par Health USA, LLC",Vasostrict,Vasopressin,42023-219,"[{'name': 'VASOPRESSIN, UNSPECIFIED', 'strengt...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '42023-219-10', 'description'...","{'concept': [['2399909', 'SBD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '100 mL', '...",VIAL,100 mL
3,"Par Health USA, LLC",Vasostrict,Vasopressin,42023-237,"[{'name': 'VASOPRESSIN, UNSPECIFIED', 'strengt...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '42023-237-10', 'description'...","{'concept': [['2591431', 'SBD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '100 mL', '...",VIAL,100 mL
4,"Amphastar Pharmaceuticals, Inc.",Vasopressin,Vasopressin,0548-9701,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '0548-9701-00', 'description'...","{'concept': [['2103182', 'SCD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '1 mL', 'pa...",VIAL,1 mL
5,"Fresenius Kabi USA, LLC",VASOPRESSIN,VASOPRESSIN,63323-930,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '63323-930-01', 'description'...","{'concept': [['2103182', 'SCD']], 'drug': [['2...",generic_name,"VIAL, SINGLE-DOSE","{'packageCount': 1, 'packageSize': '1 mL', 'pa...","VIAL, SINGLE-DOSE",1 mL
6,"Dr. Reddy's Laboratories, Inc.",vasopressin,Vasopressin,43598-914,"[{'name': 'VASOPRESSIN, UNSPECIFIED', 'strengt...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '43598-914-06', 'description'...","{'concept': [['2103182', 'SCD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '1 mL', 'pa...",VIAL,1 mL
7,"American Regent, Inc.",Vasopressin,Vasopressin,0517-1020,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0517-1020-25', 'description'...","{'concept': [['2103182', 'SCD']], 'drug': [['2...",generic_name,"VIAL, SINGLE-DOSE","{'packageCount': 1, 'packageSize': '1 mL', 'pa...","VIAL, SINGLE-DOSE",1 mL
8,"Medical Purchasing Solutions, LLC",Vasostrict,Vasopressin,71872-7264,"[{'name': 'VASOPRESSIN, UNSPECIFIED', 'strengt...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '71872-7264-1', 'description'...","{'concept': [['2103184', 'SBD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '1 mL', 'pa...",VIAL,1 mL
9,"American Regent, Inc.",Vasopressin,Vasopressin,0517-1030,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0517-1030-01', 'description'...","{'concept': [['313578', 'SCD']], 'drug': [['31...",generic_name,"VIAL, MULTI-DOSE","{'packageCount': 1, 'packageSize': '10 mL', 'p...","VIAL, MULTI-DOSE",10 mL
10,"HF Acquisition Co LLC, DBA HealthFirst",VASOPRESSIN,VASOPRESSIN,51662-1623,"[{'name': 'VASOPRESSIN, UNSPECIFIED', 'strengt...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '51662-1623-1', 'description'...","{'concept': [['313578', 'SCD']], 'drug': [['31...",generic_name,"VIAL, MULTI-DOSE",None,NaN,NaN
11,"HF Acquisition Co LLC, DBA HealthFirst",VASOPRESSIN,VASOPRESSIN,51662-1314,"[{'name': 'VASOPRESSIN, UNSPECIFIED', 'strengt...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '51662-1314-1', 'description'...","{'concept': [['2103182', 'SCD']], 'drug': [['2...",generic_name,VIAL,None,NaN,NaN
12,Sagent Pharmaceuticals,Vasopressin,Vasopressin,25021-474,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '25021-474-01', 'description'...","{'concept': [['2103182', 'SCD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '1 mL', 'pa...",VIAL,1 mL
13,"Fresenius Kabi USA, LLC",VASOPRESSIN,VASOPRESSIN,65219-039,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '65219-039-01', 'description'...","{'concept': [['2103182', 'SCD']], 'drug': [['2...",generic_name,"VIAL, SINGLE-DOSE","{'packageCount': 1, 'packageSize': '1 mL', 'pa...","VIAL, SINGLE-DOSE",1 mL
14,"Medical Purchasing Solutions, LLC",VASOPRESSIN,VASOPRESSIN,71872-7306,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '71872-7306-1', 'description'...","{'concept': [['313578', 'SCD']], 'drug': [['31...",generic_name,"VIAL, MULTI-DOSE","{'packageCount': 1, 'packageSize': '1 mL', 'pa...","VIAL, MULTI-DOSE",1 mL
15,"Civica, Inc.",Vasopressin,Vasopressin,72572-860,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '72572-860-25', 'description'...","{'concept': [['2103182', 'SCD']], 'drug': [['2...",generic_name,"VIAL, SINGLE-DOSE","{'packageCount': 1, 'packageSize': '1 mL', 'pa...","VIAL, SINGLE-DOSE",1 mL
16,"HF Acquisition Co LLC, DBA HealthFirst",VASOPRESSIN,VASOPRESSIN,51662-1682,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '51662-1682-1', 'description'...","{'concept': [['313578', 'SCD']], 'drug': [['31...",generic_name,VIAL,None,NaN,NaN
17,Amneal Pharmaceuticals LLC,vasopressin,vasopressin,70121-1642,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '70121-1642-2', 'description'...","{'concept': [['2103182', 'SCD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '1 mL', 'pa...",VIAL,1 mL
18,Gland Pharma Limited,Vasopressin,Vasopressin,68083-520,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '68083-520-10', 'description'...","{'concept': [['2103182', 'SCD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '1 mL', 'pa...",VIAL,1 mL
19,"HF Acquisition Co LLC, DBA HealthFirst",VASOPRESSIN,VASOPRESSIN,51662-1688,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '51662-1688-1', 'description'...","{'concept': [['2103182', 'SCD']], 'drug': [['2...",generic_name,VIAL,None,NaN,NaN
20,"Medical Purchasing Solutions, LLC",vasopressin,Vasopressin,71872-7334,"[{'name': 'VASOPRESSIN, UNSPECIFIED', 'strengt...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '71872-7334-1', 'description'...","{'concept': [['2103182', 'SCD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '1 mL', 'pa...",VIAL,1 mL
21,"Medical Purchasin Solutions, LLC",Vasostrict,Vasopressin,71872-7014,"[{'name': 'VASOPRESSIN, UNSPECIFIED', 'strengt...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '71872-7014-1', 'description'...","{'concept': [['1593738', 'SBD']], 'drug': [['3...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '1 mL', 'pa...",VIAL,1 mL
22,Eugia US LLC,VASOPRESSIN,VASOPRESSIN,55150-370,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '55150-370-24', 'description'...","{'concept': [['313578', 'SCD']], 'drug': [['31...",generic_name,"VIAL, MULTI-DOSE","{'packageCount': 1, 'packageSize': '1 mL', 'pa...","VIAL, MULTI-DOSE",1 mL
23,Eugia US LLC,VASOPRESSIN,VASOPRESSIN,55150-370,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '55150-370-01', 'description'...","{'concept': [['313578', 'SCD']], 'drug': [['31...",generic_name,"VIAL, MULTI-DOSE","{'packageCount': 1, 'packageSize': '1 mL', 'pa...","VIAL, MULTI-DOSE",1 mL
24,"Par Health USA, LLC",Vasostrict,Vasopressin,42023-164,"[{'name': 'VASOPRESSIN, UNSPECIFIED', 'strengt...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '42023-164-10', 'description'...","{'concept': [['2103184', 'SBD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '1 mL', 'pa...",VIAL,1 mL
25,ProPharma Distribution,VASOPRESSIN,VASOPRESSIN,84549-370,"[{'name': 'VASOPRESSIN', 'strength': 20.0 unit...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '84549-370-25', 'description'...","{'concept': [['313578', 'SCD']], 'drug': [['31...",generic_name,"VIAL, MULTI-DOSE",None,NaN,NaN
26,"Par Health USA, LLC",Vasostrict,Vasopressin,42023-164,"[{'name': 'VASOPRESSIN, UNSPECIFIED', 'strengt...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '42023-164-83', 'description'...","{'concept': [['2103184', 'SBD']], 'drug': [['2...",generic_name,VIAL,"{'packageCount': 1, 'packageSize': '1 mL', 'pa...",VIAL,1 mL
27,Baxter Healthcare Corporation,Vasopressin in 0.9% Sodium Chloride,Vasopressin in 0.9% Sodium Chloride,0338-9640,"[{'name': 'VASOPRESSIN', 'strength': 0.2 unit ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '0338-9640-12', 'description'...","{'concept': [['2591428', 'SCD']], 'drug': [['2...",generic_name,BAG,"{'packageCount': 1, 'packageSize': '100 mL', '...",BAG,100 mL
28,Baxter Healthcare Corporation,Vasopressin in 0.9% Sodium Chloride,Vasopressin in 0.9% Sodium Chloride,0338-9647,"[{'name': 'VASOPRESSIN', 'strength': 0.4 unit ...",INJECTION,[INTRAVENOUS],"[{'package_ndc': '0338-9647-12', 'description'...","{'concept': [['2399907', 'SCD']], 'drug': [['2...",generic_name,BAG,"{'packageCount': 1, 'packageSize': '100 mL', '...",BAG,100 mL

In [12]:
unasyn = lookup_generic_name("ampicillin")
unasyn = extract_product_type(unasyn)
df = pd.DataFrame(unasyn)
df

,labeler_name,brand_name,generic_name,product_ndc,active_ingredients,dosage_form,route,packaging,rxcui,_matched_via,product_type,packaged_as,package_type,package_size
0,Sagent Pharmaceuticals,ampicillin,ampicillin,25021-136,"[{'name': 'AMPICILLIN SODIUM', 'strength': '1 ...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '25021-136-10', 'description'...",None,generic_name,VIAL,None,NaN,NaN
1,Sagent Pharmaceuticals,ampicillin,ampicillin,25021-137,"[{'name': 'AMPICILLIN SODIUM', 'strength': '2 ...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '25021-137-20', 'description'...",None,generic_name,VIAL,None,NaN,NaN
2,Aurobindo Pharma Limited,Ampicillin,Ampicillin,59651-551,"[{'name': 'AMPICILLIN TRIHYDRATE', 'strength':...",CAPSULE,[ORAL],"[{'package_ndc': '59651-551-01', 'description'...",None,generic_name,CAPSULE,None,NaN,NaN
3,Aurobindo Pharma Limited,Ampicillin,Ampicillin,59651-550,"[{'name': 'AMPICILLIN TRIHYDRATE', 'strength':...",CAPSULE,[ORAL],"[{'package_ndc': '59651-550-01', 'description'...",None,generic_name,CAPSULE,None,NaN,NaN
4,"Civica, Inc.",AMPICILLIN,Ampicillin,72572-017,"[{'name': 'AMPICILLIN SODIUM', 'strength': '2 ...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '72572-017-10', 'description'...",None,generic_name,"VIAL, GLASS",None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"Henry Schein, Inc.",AMPICILLIN,AMPICILLIN SODIUM,0404-9818,"[{'name': 'AMPICILLIN SODIUM', 'strength': '2 ...","INJECTION, POWDER, FOR SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0404-9818-99', 'description'...",None,generic_name,VIAL,None,NaN,NaN
96,Aurobindo Pharma Limited,NaN,Ampicillin Sodium (Sterile),65862-282,"[{'name': 'AMPICILLIN SODIUM', 'strength': '50...",POWDER,None,"[{'package_ndc': '65862-282-37', 'description'...",None,generic_name,CANISTER,None,NaN,NaN
97,Meitheal Pharmaceuticals Inc.,Ampicillin and Sulbactam,Ampicillin sodium and Sulbactam sodium,71288-032,"[{'name': 'AMPICILLIN SODIUM', 'strength': '2 ...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '71288-032-21', 'description'...",None,generic_name,"VIAL, SINGLE-DOSE",None,NaN,NaN
98,EUMEDICA PHARMACEUTICALS INDUSTRIES SOCIEDAD L...,NaN,Ampicillin and Sulbactam Sodium,84344-002,"[{'name': 'AMPICILLIN SODIUM', 'strength': '33...",POWDER,None,"[{'package_ndc': '84344-002-01', 'description'...",None,generic_name,BAG,None,NaN,NaN
99,Meitheal Pharmaceuticals Inc.,Ampicillin and Sulbactam,Ampicillin sodium and Sulbactam sodium,71288-031,"[{'name': 'AMPICILLIN SODIUM', 'strength': '1 ...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '71288-031-92', 'description'...",None,generic_name,"VIAL, SINGLE-DOSE",None,NaN,NaN

In [21]:
bupiv = lookup_generic_name(ingredient_names=['bupivacaine'], dosage_form="INJECTION", fetch_rxcui=True)
JSON(bupiv)

In [13]:
result = jsonata.Jsonata("$.[active_ingredients.[name, strength]]").evaluate(vaso)

In [14]:
dxs = jsonata.Jsonata("**.description").evaluate(vaso)
for dx in dxs:
      print(dx)
print(re.findall(r'\b[A-Z|\s|,|\-]{3,}', dx)[-1])

1 VIAL in 1 CARTON (42023-190-01)  / 10 mL in 1 VIAL
10 VIAL in 1 CARTON (68083-663-10)  / 100 mL in 1 VIAL
10 VIAL in 1 CARTON (42023-219-10)  / 100 mL in 1 VIAL (42023-219-01)
10 VIAL in 1 CARTON (42023-237-10)  / 100 mL in 1 VIAL (42023-237-01)
1 VIAL in 1 CARTON (0548-9701-00)  / 1 mL in 1 VIAL
25 VIAL, SINGLE-DOSE in 1 TRAY (63323-930-01)  / 1 mL in 1 VIAL, SINGLE-DOSE (63323-930-00)
25 VIAL in 1 CARTON (43598-914-06)  / 1 mL in 1 VIAL (43598-914-11)
25 VIAL in 1 CARTON (43598-914-25)  / 1 mL in 1 VIAL (43598-914-11)
25 VIAL, SINGLE-DOSE in 1 CARTON (0517-1020-25)  / 1 mL in 1 VIAL, SINGLE-DOSE (0517-1020-01)
1 VIAL in 1 BAG (71872-7264-1)  / 1 mL in 1 VIAL
1 VIAL, MULTI-DOSE in 1 CARTON (0517-1030-01)  / 10 mL in 1 VIAL, MULTI-DOSE
1 mL in 1 VIAL, MULTI-DOSE (51662-1623-1)
1 VIAL, MULTI-DOSE in 1 POUCH (51662-1623-2)  / 1 mL in 1 VIAL, MULTI-DOSE
1 mL in 1 VIAL (51662-1314-1)
1 VIAL in 1 POUCH (51662-1314-2)  / 1 mL in 1 VIAL
25 VIAL in 1 CARTON (25021-474-01)  / 1 mL in 1 VIAL
25 VIAL, SINGLE-DOSE in 1 TRAY (65219-039-01)  / 1 mL in 1 VIAL, SINGLE-DOSE (65219-039-00)
1 VIAL, MULTI-DOSE in 1 BAG (71872-7306-1)  / 1 mL in 1 VIAL, MULTI-DOSE
25 VIAL, SINGLE-DOSE in 1 CARTON (72572-860-25)  / 1 mL in 1 VIAL, SINGLE-DOSE
10 mL in 1 VIAL (51662-1682-1)
1 VIAL in 1 CARTON (70121-1642-2)  / 1 mL in 1 VIAL (70121-1642-1)
25 VIAL in 1 CARTON (70121-1642-5)  / 1 mL in 1 VIAL (70121-1642-1)
10 VIAL in 1 CARTON (70121-1642-7)  / 1 mL in 1 VIAL (70121-1642-1)
10 VIAL in 1 CARTON (68083-520-10)  / 1 mL in 1 VIAL
25 VIAL in 1 CARTON (68083-520-25)  / 1 mL in 1 VIAL
1 mL in 1 VIAL (51662-1688-1)
1 VIAL in 1 BAG (71872-7334-1)  / 1 mL in 1 VIAL
1 VIAL in 1 BAG (71872-7014-1)  / 1 mL in 1 VIAL
25 VIAL, MULTI-DOSE in 1 CARTON (55150-370-24)  / 1 mL in 1 VIAL, MULTI-DOSE
1 VIAL, MULTI-DOSE in 1 CARTON (55150-370-01)  / 1 mL in 1 VIAL, MULTI-DOSE
25 VIAL, MULTI-DOSE in 1 CARTON (55150-370-25)  / 1 mL in 1 VIAL, MULTI-DOSE
10 VIAL in 1 CARTON (42023-164-10)  / 1 mL in 1 VIAL (42023-164-01)
25 VIAL in 1 CARTON (42023-164-25)  / 1 mL in 1 VIAL (42023-164-01)
1 mL in 1 VIAL, MULTI-DOSE (84549-370-25)
25 VIAL in 1 CARTON (42023-164-83)  / 1 mL in 1 VIAL
12 BAG in 1 CARTON (0338-9640-12)  / 100 mL in 1 BAG
12 BAG in 1 CARTON (0338-9647-12)  / 100 mL in 1 BAG
 BAG

In [15]:
# language=JSONata
res = jsonata.Jsonata("""$.{labeler_name:
                        [active_ingredients.{
                              'name': name,
                              'strength': strength,
                              'product_type': product_type,
                              'product_ndc': %.product_ndc
                        },
                        [**.description]]
                  }""").evaluate(vaso)
# data = parse_strength_in_context(res)
JSON(res)

### Penicillin G

In [22]:
pen_g = lookup_generic_name("penicillin g", fetch_rxcui=True)
df = pd.DataFrame(pen_g)
df['api'] = df['active_ingredients'].apply(lambda ings: ings[0]['name'] if ings else None)
df['api_strength'] = df['active_ingredients'].apply(lambda ings: ings[0]['strength'] if ings else None)
df['api_2'] = df['active_ingredients'].apply(lambda ings: ings[1]['name'] if len(ings) > 1 else None)
df['api_2_strength'] = df['active_ingredients'].apply(lambda ings: ings[1]['strength'] if len(ings) > 1 else None)
df

,labeler_name,brand_name,generic_name,product_ndc,active_ingredients,dosage_form,route,packaging,rxcui,_matched_via,product_type,packaged_as,package_type,package_size,api,api_strength,api_2,api_2_strength
0,Baxter Healthcare Corporation,PENICILLIN G POTASSIUM,PENICILLIN G,0338-1021,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0338-1021-41', 'description'...","{'concept': [['207390', 'SCD']], 'drug': [['20...",generic_name,BAG,None,NaN,NaN,PENICILLIN G POTASSIUM,1000000 [iU]/50mL,NaN,NaN
1,Baxter Healthcare Corporation,PENICILLIN G POTASSIUM,PENICILLIN G,0338-1023,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0338-1023-41', 'description'...","{'concept': [['204466', 'SCD']], 'drug': [['20...",generic_name,BAG,None,NaN,NaN,PENICILLIN G POTASSIUM,2000000 [iU]/50mL,NaN,NaN
2,Baxter Healthcare Corporation,PENICILLIN G POTASSIUM,PENICILLIN G,0338-1025,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0338-1025-41', 'description'...","{'concept': [['207391', 'SCD']], 'drug': [['20...",generic_name,BAG,None,NaN,NaN,PENICILLIN G POTASSIUM,3000000 [iU]/50mL,NaN,NaN
3,Roerig,Pfizerpen,penicillin G potassium,0049-0530,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","POWDER, FOR SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0049-0530-22', 'description'...","{'concept': [['995906', 'SBD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,20000000 [iU]/1,NaN,NaN
4,"NorthStar Rx, LLC",Penicillin G Potassium,Penicillin G Potassium,72603-345,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION",[INTRAVENOUS],"[{'package_ndc': '72603-345-01', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,20000000 [iU]/1,NaN,NaN
5,Sagent Pharmaceuticals,Penicillin G Potassium,penicillin g potassium,25021-153,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '25021-153-20', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,5000000 [iU]/1,NaN,NaN
6,Sagent Pharmaceuticals,Penicillin G Potassium,penicillin g potassium,25021-154,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION",[INTRAVENOUS],"[{'package_ndc': '25021-154-51', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,20000000 [iU]/1,NaN,NaN
7,Sandoz Inc,Penicillin G Potassium,Penicillin G Potassium,0781-6135,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '0781-6135-95', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,5000000 [iU]/1,NaN,NaN
8,Sandoz Inc,Penicillin G Potassium,Penicillin G Potassium,0781-6136,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '0781-6136-94', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,20000000 [iU]/1,NaN,NaN
9,Avenacy Inc.,Penicillin G Potassium,penicillin g potassium,83634-103,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION",[INTRAVENOUS],"[{'package_ndc': '83634-103-51', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,20000000 [iU]/1,NaN,NaN
10,Roerig,Pfizerpen,penicillin G potassium,0049-0430,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","POWDER, FOR SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0049-0430-20', 'description'...","{'concept': [['995906', 'SBD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,20000000 [iU]/1,NaN,NaN
11,Avenacy Inc.,Penicillin G Potassium,penicillin g potassium,83634-102,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '83634-102-20', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,5000000 [iU]/1,NaN,NaN
12,Sandoz Inc,Penicillin G Sodium,Penicillin G Sodium,0781-6153,"[{'name': 'PENICILLIN G SODIUM', 'strength': '...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '0781-6153-95', 'description'...","{'concept': [['745302', 'SCD']], 'drug': [['74...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G SODIUM,5000000 [USP'U]/1,NaN,NaN
13,"LABORATRIOS ATRAL, S.A.",Lentocilin,Penicillin G Benzathin,84383-110,"[{'name': 'PENICILLIN G BENZATHINE', 'strength...","INJECTION, POWDER, FOR SUSPENSION",[INTRAMUSCULAR],"[{'package_ndc': '84383-110-01', 'description'...","{'concept': [['2684991', 'SBD']], 'drug': [['2...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G BENZATHINE,1200000 U/4mL,NaN,NaN
14,Pfizer Laboratories Div Pfizer Inc,BICILLIN CR,penicillin G benzathine and penicillin G procaine,60793-600,"[{'name': 'PENICILLIN G BENZATHINE', 'strength...","INJECTION, SUSPENSION",[INTRAMUSCULAR],"[{'package_ndc': '60793-600-10', 'description'...","{'concept': [['731541', 'SBD']], 'drug': [['73...",generic_name,SYRINGE,"{'packageCount': 1, 'packageSize': '2 mL', 'pa...",SYRINGE,2 mL,PENICILLIN G BENZATHINE,600000 [iU]/2mL,PENICILLIN G PROCAINE,600000 [iU]/2mL
15,Pfizer Laboratories Div Pfizer Inc,BICILLIN L-A,penicillin G benzathine,60793-701,"[{'name': 'PENICILLIN G BENZATHINE', 'strength...","INJECTION, SUSPENSION",[INTRAMUSCULAR],"[{'package_ndc': '60793-701-10', 'description'...","{'concept': [['731568', 'SBD']], 'drug': [['73...",generic_name,SYRINGE,"{'packageCount': 1, 'packageSize': '2 mL', 'pa...",SYRINGE,2 mL,PENICILLIN G BENZATHINE,1200000 [iU]/2mL,NaN,NaN
16,Pfizer Laboratories Div Pfizer Inc,BICILLIN CR,penicillin G benzathine and penicillin G procaine,60793-601,"[{'name': 'PENICILLIN G BENZATHINE', 'strength...","INJECTION, SUSPENSION",[INTRAMUSCULAR],"[{'package_ndc': '60793-601-10', 'description'...","{'concept': [['731541', 'SBD']], 'drug': [['73...",generic_name,SYRINGE,"{'packageCount': 1, 'packageSize': '2 mL', 'pa...",SYRINGE,2 mL,PENICILLIN G BENZATHINE,600000 [iU]/2mL,PENICILLIN G PROCAINE,600000 [iU]/2mL
17,"Sinopharm Weiqida Pharmaceutical Co., Ltd.",NaN,PENICILLIN G POTASSIUM,55657-103,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...",POWDER,None,"[{'package_ndc': '55657-103-25', 'description'...",{},generic_name,DRUM,None,NaN,NaN,PENICILLIN G POTASSIUM,1 kg/kg,NaN,NaN
18,Pfizer Laboratories Div Pfizer Inc,BICILLIN C-R 900/300,penicillin G benzathine and penicillin G procaine,60793-602,"[{'name': 'PENICILLIN G BENZATHINE', 'strength...","INJECTION, SUSPENSION",[INTRAMUSCULAR],"[{'package_ndc': '60793-602-10', 'description'...","{'concept': [['836307', 'SBD']], 'drug': [['83...",generic_name,SYRINGE,"{'packageCount': 1, 'packageSize': '2 mL', 'pa...",SYRINGE,2 mL,PENICILLIN G BENZATHINE,900000 [iU]/2mL,PENICILLIN G PROCAINE,300000 [iU]/2mL
19,Pfizer Laboratories Div Pfizer Inc,BICILLIN L-A,penicillin G benzathine,60793-700,"[{'name': 'PENICILLIN G BENZATHINE', 'strength...","INJECTION, SUSPENSION",[INTRAMUSCULAR],"[{'package_ndc': '60793-700-10', 'description'...","{'concept': [['731566', 'SBD']], 'drug': [['73...",generic_name,SYRINGE,"{'packageCount': 1, 'packageSize': '1 mL', 'pa...",SYRINGE,1 mL,PENICILLIN G BENZATHINE,600000 [iU]/mL,NaN,NaN
20,Pfizer Laboratories Div Pfizer Inc,BICILLIN L-A,penicillin G benzathine,60793-702,"[{'name': 'PENICILLIN G BENZATHINE', 'strength...","INJECTION, SUSPENSION",[INTRAMUSCULAR],"[{'package_ndc': '60793-702-10', 'description'...","{'concept': [['731571', 'SBD']], 'drug': [['73...",generic_name,SYRINGE,"{'packageCount': 1, 'packageSize': '4 mL', 'pa...",SYRINGE,4 mL,PENICILLIN G BENZATHINE,2400000 [iU]/4mL,NaN,NaN
21,"NorthStar Rx, LLC",Penicillin G Potassium,Penicillin G Potassium,72603-210,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '72603-210-01', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,5000000 [iU]/1,NaN,NaN
22,"Fersinsa GB, S.A. de C.V",NaN,Penicillin G Potassium,58775-001,"[{'name': 'PENICILLIN G', 'strength': '1 kg/kg'}]",POWDER,None,"[{'package_ndc': '58775-001-00', 'description'...",{},generic_name,BOX,None,NaN,NaN,PENICILLIN G,1 kg/kg,NaN,NaN
23,"Fersinsa GB, S.A. de C.V.",NaN,PENICILLIN G PROCAINE,58775-002,"[{'name': 'PENICILLIN G PROCAINE', 'strength':...",POWDER,None,"[{'package_ndc': '58775-002-00', 'description'...",{},generic_name,BOX,None,NaN,NaN,PENICILLIN G PROCAINE,1 kg/kg,NaN,NaN
24,Roerig,Pfizerpen,penicillin G potassium,0049-0520,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAPLEURAL, INTRATHECAL, INT...","[{'package_ndc': '0049-0520-22', 'description'...","{'concept': [['995906', 'SBD'], ['863538', 'SC...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,5000000 [iU]/1,NaN,NaN
25,Roerig,Pfizerpen,penicillin G potassium,0049-0530,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","POWDER, FOR SOLUTION",[INTRAVENOUS],"[{'package_ndc': '0049-0530-28', 'description'...","{'concept': [['995906', 'SBD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,20000000 [iU]/1,NaN,NaN
26,"Athenex Pharmaceutical Division, LLC.",Penicillin G Potassium,penicillin g potassium,70860-127,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION",[INTRAVENOUS],"[{'package_ndc': '70860-127-51', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,20000000 [iU]/1,NaN,NaN
27,ACS Dobfar S.p.A,NaN,Penicillin G Potassium,52946-0703,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...",POWDER,None,"[{'package_ndc': '52946-0703-0', 'description'...",{},generic_name,BOX,None,NaN,NaN,PENICILLIN G POTASSIUM,1 kg/kg,NaN,NaN
28,"WG Critical Care, LLC",Penicillin G Potassium,Penicillin G Potassium,44567-311,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '44567-311-10', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,5000000 [iU]/1,NaN,NaN
29,"WG Critical Care, LLC",Penicillin G Potassium,Penicillin G Potassium,44567-310,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '44567-310-10', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,1000000 [iU]/1,NaN,NaN
30,"WG Critical Care, LLC",Penicillin G Potassium,Penicillin G Potassium,44567-312,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION",[INTRAVENOUS],"[{'package_ndc': '44567-312-01', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,20000000 [iU]/1,NaN,NaN
31,Roerig,Pfizerpen,penicillin G potassium,0049-0520,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAPLEURAL, INTRATHECAL, INT...","[{'package_ndc': '0049-0520-83', 'description'...","{'concept': [['995906', 'SBD'], ['863538', 'SC...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,5000000 [iU]/1,NaN,NaN
32,"HF Acquisition Co LLC, DBA HealthFirst",PENICILLIN G POTASSIUM,PENICILLIN G POTASSIUM,51662-1689,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '51662-1689-1', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,"INJECTION, POWDER, FOR SOLUTION",None,NaN,NaN,PENICILLIN G POTASSIUM,5000000 [iU]/1,NaN,NaN
33,CSPC Zhongnuo Pharmaceutical (Shijiazhuang) Co...,NaN,Penicillin G Procaine,52962-630,"[{'name': 'PENICILLIN G PROCAINE', 'strength':...",POWDER,None,"[{'package_ndc': '52962-630-11', 'description'...",{},generic_name,BAG,"{'packageCount': 1, 'packageSize': '5 kg', 'pa...",BAG,5 kg,PENICILLIN G PROCAINE,1 kg/kg,NaN,NaN
34,A-S Medication Solutions,BICILLIN L-A,penicillin G benzathine,50090-1016,"[{'name': 'PENICILLIN G BENZATHINE', 'strength...","INJECTION, SUSPENSION",[INTRAMUSCULAR],"[{'package_ndc': '50090-1016-0', 'description'...","{'concept': [['731568', 'SBD']], 'drug': [['73...",generic_name,SYRINGE,"{'packageCount': 1, 'packageSize': '2 mL', 'pa...",SYRINGE,2 mL,PENICILLIN G BENZATHINE,1200000 [iU]/2mL,NaN,NaN
35,Roerig,Pfizerpen,penicillin G potassium,0049-0420,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAPLEURAL, INTRATHECAL, INT...","[{'package_ndc': '0049-0420-10', 'description'...","{'concept': [['995906', 'SBD']], 'drug': [['99...",generic_name,VIAL,None,NaN,NaN,PENICILLIN G POTASSIUM,5000000 [iU]/1,NaN,NaN
36,"North China Pharmaceutical Co., Ltd. Beta Bran...",NaN,Penicillin G Potassium,87488-101,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...",POWDER,None,"[{'package_ndc': '87488-101-01', 'description'...",{},generic_name,BOX,None,NaN,NaN,PENICILLIN G POTASSIUM,1 kg/kg,NaN,NaN
37,Aurobindo Pharma Limited,NaN,Penicillin G Benzathine,84386-021,"[{'name': 'PENICILLIN G BENZATHINE', 'strength...",POWDER,None,"[{'package_ndc': '84386-021-37', 'description'...",{},generic_name,CANISTER,None,NaN,NaN,PENICILLIN G BENZATHINE,50 kg/50kg,NaN,NaN
38,Fresenius Kabi iPSUM S.r.l.,NaN,PENICILLIN G SODIUM,66558-0170,"[{'name': 'PENICILLIN G SODIUM', 'strength': '...",POWDER,None,"[{'package_ndc': '66558-0170-7', 'description'...",{},generic_name,CONTAINER,None,NaN,NaN,PENICILLIN G SODIUM,1 kg/kg,NaN,NaN
39,Fresenius Kabi iPSUM S.r.l.,NaN,PENICILLIN G BENZATHINE,66558-0198,"[{'name': 'PENICILLIN G BENZATHINE', 'strength...",POWDER,None,"[{'package_ndc': '66558-0198-1', 'description'...",{},generic_name,CONTAINER,None,NaN,NaN,PENICILLIN G BENZATHINE,1 kg/kg,NaN,NaN
40,Sandoz GmbH,NaN,Sterile Penicillin G Procaine,43858-502,"[{'name': 'PENICILLIN G PROCAINE', 'strength':...",POWDER,None,"[{'package_ndc': '43858-502-00', 'description'...",{},generic_name,DRUM,None,NaN,NaN,PENICILLIN G PROCAINE,10 kg/10kg,NaN,NaN
41,Sandoz GmbH,NaN,Sterile Penicillin G Procaine,43858-500,"[{'name': 'PENICILLIN G PROCAINE', 'strength':...",POWDER,None,"[{'package_ndc': '43858-500-00', 'description'...",{},generic_name,DRUM,None,NaN,NaN,PENICILLIN G PROCAINE,10 kg/10kg,NaN,NaN
42,Sandoz GmbH,NaN,Sterile Penicillin G Procaine,43858-501,"[{'name': 'PENICILLIN G PROCAINE', 'strength':...",POWDER,None,"[{'package_ndc': '43858-501-00', 'description'...",{},generic_name,BOX,None,NaN,NaN,PENICILLIN G PROCAINE,10 kg/10kg,NaN,NaN
43,Sandoz GmbH,NaN,Sterile Penicillin G Benzathine,43858-510,"[{'name': 'PENICILLIN G BENZATHINE', 'strength...",POWDER,None,"[{'package_ndc': '43858-510-00', 'description'...",{},generic_name,DRUM,None,NaN,NaN,PENICILLIN G BENZATHINE,10 kg/10kg,NaN,NaN
44,Sandoz GmbH,NaN,Sterile Penicillin G Benzathine,43858-511,"[{'name': 'PENICILLIN G BENZATHINE', 'strength...",POWDER,None,"[{'package_ndc': '43858-511-00', 'description'...",{},generic_name,BOX,None,NaN,NaN,PENICILLIN G BENZATHINE,10 kg/10kg,NaN,NaN
45,"HF Acquisition Co LLC, DBA HealthFirst",BUFFERED PENICILLIN G POTASSIUM,BUFFERED PENICILLIN G POTASSIUM,51662-1436,"[{'name': 'PENICILLIN G POTASSIUM', 'strength'...","INJECTION, POWDER, FOR SOLUTION","[INTRAMUSCULAR, INTRAVENOUS]","[{'package_ndc': '51662-1436-1', 'description'...","{'concept': [['863538', 'SCD']], 'drug': [['99...",generic_name,"INJECTION, POWDER, FOR SOLUTION",None,NaN,NaN,PENICILLIN G POTASSIUM,5000000 [iU]/1,NaN,NaN

In [ ]:
df[df['labeler_name'].str.contains('Roerig', na=False)]

# Filterable Drugs

In [ ]:
def get_inline_filter_drugs():
      url = r"http://pmc.ncbi.nlm.nih.gov/articles/PMC11907493/table/table1-00185787251324867"
      df = pd.read_html(url)[0]
      # remove NBSP chars
      df['Drug'] = df['Drug'].str.replace(r'\xa0', ' ')
      df['brand'] = df['Drug'].str.findall(r'\((.*?)\)')
      return df


filterable_drugs = get_inline_filter_drugs()
filterable_drugs

# RXCUI